### Read data from `NPAtlas` data base

In [5]:
import warnings
import pandas as pd
from rdkit import Chem
from rdkit.Chem import PandasTools
from rdkit import RDLogger
RDLogger.DisableLog('rdApp.*')

# Suppress all warnings
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    npatlasDF = PandasTools.LoadSDF('NPAtlas_np_data.sdf', smilesName='SMILES', molColName='Molecule')

# View the DataFrame
print(f"Shape: {npatlasDF.shape}")
print(f"Columns: {npatlasDF.columns.tolist()}")
npatlasDF

Failed to patch pandas - unable to change molecule rendering

Shape: (36454, 37)
Columns: ['npaid', 'compound_id', 'compound_name', 'compound_molecular_formula', 'compound_molecular_weight', 'compound_accurate_mass', 'compound_m_plus_h', 'compound_m_plus_na', 'compound_inchi', 'compound_inchikey', 'compound_smiles', 'compound_cluster_id', 'compound_node_id', 'origin_type', 'genus', 'origin_species', 'original_reference_author_list', 'original_reference_year', 'original_reference_issue', 'original_reference_volume', 'original_reference_pages', 'original_reference_doi', 'original_reference_pmid', 'original_reference_title', 'original_reference_type', 'original_journal_title', 'synonyms_dois', 'reassignment_dois', 'synthesis_dois', 'mibig_ids', 'gnps_ids', 'cmmc_ids', 'npmrd_id', 'npatlas_url', 'ID', 'SMILES', 'Molecule']

,npaid,compound_id,compound_name,compound_molecular_formula,compound_molecular_weight,compound_accurate_mass,compound_m_plus_h,compound_m_plus_na,compound_inchi,compound_inchikey,...,reassignment_dois,synthesis_dois,mibig_ids,gnps_ids,cmmc_ids,npmrd_id,npatlas_url,ID,SMILES,Molecule
0,NPA000001,1,Curvularide C,C19H37NO5,359.5070,359.2672,360.2745,382.2564,InChI=1S/C19H37NO5/c1-7-13(3)16(12-21)20-17(23...,BZLIDAVUQDTJQF-HWTFSWDCSA-N,...,,,,,,NP0009379,https://www.npatlas.org/explore/compounds/NPA0...,NPA000001,CC[C@@H](O)C[C@H](C)[C@H](O)[C@@](C)(/C=C/C(=O...,<rdkit.Chem.rdchem.Mol object at 0x7f33c459e1f0>
1,NPA000002,2,Homopetasinic acid,C24H32O6,416.5140,416.2199,417.2272,439.2091,InChI=1S/C24H32O6/c1-14(2)18-13-24(5)16(4)21(1...,MMWCHIIGAIJQMV-DHCANEKFSA-N,...,,,,,,NP0250242,https://www.npatlas.org/explore/compounds/NPA0...,NPA000002,C=C(C)[C@@H]1C[C@@]2(C)C(=CC1=O)CC[C@@H](OC(=O...,<rdkit.Chem.rdchem.Mol object at 0x7f32ccf4d460>
2,NPA000003,3,A-503083 F,C18H22N4O13,502.3890,502.1183,503.1256,525.1075,InChI=1S/C18H22N4O13/c1-31-9-10(11(13(19)26)34...,RNRCUOCMUNIOMZ-UHFFFAOYSA-N,...,,,BGC0000288,,,NP0005648,https://www.npatlas.org/explore/compounds/NPA0...,NPA000003,COC1C(C(OC2OC(C(=O)O)=CC(O)C2O)C(N)=O)OC(n2ccc...,<rdkit.Chem.rdchem.Mol object at 0x7f32ccf4d4d0>
3,NPA000004,4,Aqabamycin E2,C16H11N3O5,325.2800,325.0699,326.0772,348.0591,InChI=1S/C16H11N3O5/c20-12-7-6-10(8-11(12)19(2...,NMMDNCZQLOFGES-UHFFFAOYSA-N,...,,,,,,NP0009185,https://www.npatlas.org/explore/compounds/NPA0...,NPA000004,O=Nc1[nH]c(O)c(-c2ccccc2)c1-c1ccc(O)c([N+](=O)...,<rdkit.Chem.rdchem.Mol object at 0x7f32ccf4da80>
4,NPA000005,5,Hymenopsin A,C22H32O6,392.4920,392.2199,393.2272,415.2091,InChI=1S/C22H32O6/c1-18(10-23)6-3-7-19(2)13-9-...,OYLVOLOSQHRPLK-WRXMSMRBSA-N,...,,,,,,NP0008877,https://www.npatlas.org/explore/compounds/NPA0...,NPA000005,C[C@@]1(CO)CCC[C@]2(C)[C@H]3C[C@@]45OC4[C@H](O...,<rdkit.Chem.rdchem.Mol object at 0x7f32ccf4d000>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36449,NPA036718,36718,Julichrome Q3-3,C38H38O16,750.7060,750.2160,751.2233,773.2052,"InChI=1S/C38H38O16/c1-13(51-15(3)39)27-33(5,49...",FCANTWZHYAQEKU-DLUJSSSPSA-N,...,"{'reference_doi': '10.1002/cbdv.202000057', 's...",,,CCMSLIB00000847609%NCGC00180378-02!%1|CCMSLIB0...,,None,https://www.npatlas.org/explore/compounds/NPA0...,NPA036718,CC(=O)O[C@H](C)[C@H]1[C@@](C)(O)CC(=O)[C@]23O[...,<rdkit.Chem.rdchem.Mol object at 0x7f32c70c5a10>
36450,NPA036719,36719,GE81112A,C24H34ClN9O10,644.0420,643.2117,644.2190,666.2009,InChI=1S/C24H34ClN9O10/c25-23-29-7-14(33-23)18...,MPRVLYUMDIXCGD-UHFFFAOYSA-N,...,,,,,,None,https://www.npatlas.org/explore/compounds/NPA0...,NPA036719,NC(=O)OCC(O)CC(NC(=O)C1NCCCC1O)C(=O)NC(Cc1cnc[...,<rdkit.Chem.rdchem.Mol object at 0x7f32c70c5af0>
36451,NPA036723,36723,Subvellerolactone C,C17H26O5,310.3900,310.1780,311.1853,333.1672,InChI=1S/C17H26O5/c1-5-17(21)12-10(14(19)22-17...,KJKLEJNFKHFYGR-PDROMXSDSA-N,...,,,,,,None,https://www.npatlas.org/explore/compounds/NPA0...,NPA036723,CC[C@]1(O)OC(=O)C2=C1[C@H](O)[C@@H]1CC(C)(C)C[...,<rdkit.Chem.rdchem.Mol object at 0x7f32c70c5bd0>
36452,NPA036726,36726,10E-cyclonerotriol,C15H28O3,256.3860,256.2038,257.2111,279.1930,"InChI=1S/C15H28O3/c1-11(10-16)6-5-8-15(4,18)13...",QGUPPGVBDCWDSK-BSYVWGKESA-N,...,,,,,,None,https://www.npatlas.org/explore/compounds/NPA0...,NPA036726,C/C(=C\CC[C@@](C)(O)[C@@H]1CC[C@@](C)(O)[C@H]1...,<rdkit.Chem.rdchem.Mol object at 0x7f32c70c5cb0>
36453,NPA036727,36727,Epicyclonerodiol Oxide,C15H28O3,256.3860,256.2038,257.2111,279.1930,"InChI=1S/C15H28O3/c1-10-11(6-8-14(10,4)17)15(5...",CTTSYRDQSMAGNT-PGKPSXLWSA-N,...,,,,,,None,https://www.npatlas.org/explore/compounds/NPA0...,NPA036727,C[C@H]1[C@H]([C@@]2(C)CC[C@H](C(C)(C)O)O2)CC[C...,<rdkit.Chem.rdchem.Mol object at 0x7f32c70c5fc0>

### Read data from `coconut` data base

In [6]:
import warnings
import pandas as pd
from rdkit import Chem
from rdkit.Chem import PandasTools
from rdkit import RDLogger
RDLogger.DisableLog('rdApp.*')

# Suppress all warnings
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    coconutDF = PandasTools.LoadSDF('coconut_np_data.sdf', smilesName='SMILES', molColName='Molecule')

# View the DataFrame
print(f"Shape: {coconutDF.shape}")
print(f"Columns: {coconutDF.columns.tolist()}")
coconutDF

Failed to patch pandas - unable to change molecule rendering

Shape: (715818, 47)
Columns: ['identifier', 'canonical_smiles', 'standard_inchi', 'standard_inchi_key', 'name', 'iupac_name', 'annotation_level', 'total_atom_count', 'heavy_atom_count', 'molecular_weight', 'exact_molecular_weight', 'molecular_formula', 'alogp', 'topological_polar_surface_area', 'rotatable_bond_count', 'hydrogen_bond_acceptors', 'hydrogen_bond_donors', 'hydrogen_bond_acceptors_lipinski', 'hydrogen_bond_donors_lipinski', 'lipinski_rule_of_five_violations', 'aromatic_rings_count', 'qed_drug_likeliness', 'formal_charge', 'fractioncsp3', 'number_of_minimal_rings', 'van_der_walls_volume', 'contains_sugar', 'contains_ring_sugars', 'contains_linear_sugars', 'murcko_framework', 'np_likeness', 'chemical_class', 'chemical_sub_class', 'chemical_super_class', 'direct_parent_classification', 'np_classifier_pathway', 'np_classifier_superclass', 'np_classifier_class', 'np_classifier_is_glycoside', 'organisms', 'collections', 'dois', 'synonyms', 'cas', 'ID', 'SMILES', 'Molecule']

,identifier,canonical_smiles,standard_inchi,standard_inchi_key,name,iupac_name,annotation_level,total_atom_count,heavy_atom_count,molecular_weight,...,np_classifier_class,np_classifier_is_glycoside,organisms,collections,dois,synonyms,cas,ID,SMILES,Molecule
0,CNP0131528.1,C/C=C(/CC[C@@H](C)[C@H]1CC[C@H]2[C@H](CCC3=CC(...,InChI=1S/C29H46O2/c1-7-22(19(2)3)10-8-21(5)26-...,LNGGVLHPASAPSR-MYTFACOISA-N,nan,"(1~{R},3~{a}~{S},4~{S},5~{R},7~{a}~{R})-4-[2-(...",5,77,31,426.69,...,Stigmastane steroids,False,Astrogorgia sp.,CMNPD,10.1039/c2np20112g,astrogorgol I,nan,,C/C=C(/CC[C@@H](C)[C@H]1CC[C@H]2[C@H](CCc3cc(O...,<rdkit.Chem.rdchem.Mol object at 0x7f32ccf4ceb0>
1,CNP0125663.1,CC(=O)O[C@H]1[C@@H](OC(C)=O)[C@]2(CO2)[C@@H]2[...,InChI=1S/C38H52O16/c1-18(2)13-28(43)47-16-25-1...,BABABLBWTGFRAX-BOZCQHDUSA-N,nan,"[(1~{S},2~{S},3~{S},4~{R},7~{S},8~{E},10~{Z},1...",4,106,54,764.82,...,Briarane diterpenoids,False,Dichotella gemmacea,CMNPD,10.1039/c4np00144c,dichotellide L,nan,,CC(=O)O[C@H]1[C@@H](OC(C)=O)[C@]2(CO2)[C@@H]2[...,<rdkit.Chem.rdchem.Mol object at 0x7f32df2d6ab0>
2,CNP0189948.1,CCCCCCC[C@@H](C/C=C/CCC(=O)N(C)C/C(=C/Cl)C1=CC...,InChI=1S/C26H42ClNO4/c1-5-6-7-8-10-13-22(32-4)...,GPOZTCNXXQOJHN-RYOWJLOQSA-N,nan,"(~{E},7~{S})-~{N}-[(~{E})-3-chloro-2-[(4~{S},5...",4,74,32,468.08,...,Lipopeptides,False,Lyngbya majuscula,CMNPD,10.1039/c2np20112g,malyngamide L,nan,,CCCCCCC[C@@H](C/C=C/CCC(=O)N(C)C/C(=C/Cl)C1=CC...,<rdkit.Chem.rdchem.Mol object at 0x7f32c70c7a70>
3,CNP0286908.0,CCCCCCC=CCCCCCCCC=O,InChI=1S/C16H30O/c1-2-3-4-5-6-7-8-9-10-11-12-1...,QFPVVMKZTVQDTL-UHFFFAOYSA-N,hexadec-9-enal,hexadec-9-enal,5,47,17,238.41,...,Fatty aldehydes,False,Acorus gramineus|Acorus tatarinowii|Geitlerine...,Australian natural products|CMAUP (cCollective...,10.1007/BF00636583|10.1016/J.JEP.2012.12.019|1...,9Z-16CHO|DA-17547|DTXSID70860698|QFPVVMKZTVQDT...,nan,,CCCCCCC=CCCCCCCCC=O,<rdkit.Chem.rdchem.Mol object at 0x7f32c70c7140>
4,CNP0316772.3,COC1=CC(O)=C2C(=O)O[C@@H](C)C/C=C/C(=O)[C@@H](...,InChI=1S/C19H22O7/c1-11-5-3-7-14(20)18(23)15(2...,NEQZWEXWOFPKOT-KMIRMROWSA-N,Cochliomycin D,"(4~{S},6~{E},9~{S},10~{R},12~{E})-9,10,18-trih...",5,48,26,362.38,...,Zearalenones,False,Curvularia lunata,CMNPD|WikiData Natural Products,10.1021/JF500248Z|10.1039/c5np00156k,"(4S,6E,9S,10R,12E)-9,10,18-trihydroxy-16-metho...",nan,,COc1cc(O)c2c(c1)/C=C/C[C@@H](O)[C@H](O)C(=O)/C...,<rdkit.Chem.rdchem.Mol object at 0x7f32c70c71b0>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
715813,CNP0119877.0,COC1=C(C2=CC=C(O)C=C2)OC2=CC(C3OC(COC(=O)C4=CC...,InChI=1S/C29H26O14/c1-40-28-23(36)20-15(31)6-1...,STPVWXKVVHTKSD-UHFFFAOYSA-N,nan,"[3,4,5-trihydroxy-6-[5-hydroxy-2-(4-hydroxyphe...",1,69,43,598.51,...,Flavonols,False,nan,UNPD (Universal Natural Products Database),nan,nan,nan,,COc1c(-c2ccc(O)cc2)oc2cc(C3OC(COC(=O)c4cc(O)c(...,<rdkit.Chem.rdchem.Mol object at 0x7f31b1ad6420>
715814,CNP0294226.1,C=C1CC[C@]2(C)C3=C(C(=O)[C@@]4(C[C@@H]4C)[C@@H...,InChI=1S/C22H26O6/c1-9-6-7-21(5)14(11(9)3)16(2...,BQBPQUHGQNQEEU-HIJRYFSGSA-N,nan,"[(2'~{S},4~{a}~{S},6~{R},7~{R},9~{S},10~{S},10...",1,54,28,386.44,...,Cycloabietane diterpenoids,False,Plectranthus garckeanus,Super Natural II|WikiData Natural Products,10.1002/HLCA.19790620734,nan,nan,,C=C1CC[C@]2(C)C3=C(C(=O)[C@@]4(C[C@@H]4C)[C@@H...,<rdkit.Chem.rdchem.Mol object at 0x7f31b1ad6490>
715815,CNP0148368.1,NC[C@H](O)C[C@@H](N)CC(=O)O,InChI=1S/C6H14N2O3/c7-3-5(9)1-4(8)2-6(10)11/h4...,LCWXJXMHJVIJFK-RFZPGFLSSA-N,"(3R,5R)-3,6-diamino-5-hydroxyhexanoic acid","(3~{R},5~{R})-3,6-diamino-5-hydroxy-hexanoic acid",3,25,11,162.19,...,Aminoacids,False,Agaricus campestris,NPASS|Super Natural II|TCMDB-Taiwan (Tradition...,nan,SCHEMBL6827797,nan,,NC[C@H](O)C[C@@H](N)CC(=O)O,<rdkit.Chem.rdchem.Mol object at 0x7f31b1ad6570>
715816,CNP0157088.1,O=C(C1=CC=CC=C1)[C@@H]1[C@@H]2CCCN2[C@]2(C(=O)...,InChI=1S/C28H22ClN3O3/c29-17-12-13-21-19(15-17...,WLWRWWMRVLYYQB-WLGONLEPSA-N,STL532904,nan,3,57,35,483.96,...,Simple oxindole alkaloids,False,nan,InterBioScreen Ltd|Super Natural II,nan,"(1'S,3R,3'S,7a'S)-5''-chloro-1'-(phenylcarbony...",nan,,O=C(c1ccccc1)[C@@H]1[C@@H]2CCCN2[C@]2(C(=O)Nc3...,<rdkit.Chem.rdchem.Mol object at 0x7f31b1ad65e0>
715817,CNP0142479.1,C#C/C=C/C[C@H]1O[C@@H]([C@@H](Br)C/C=C/CC)C[C@...,InChI=1S/C17H23BrO3/c1-4-6-8-10-14(18)16-12-17...,BUFQJMZKMZGEFE-GIGMYMNUSA-N,nan,"[(2~{R},3~{R},5~{R})-5-[(~{E},1~{S})-1-bromohe...",2,44,21,355.27,...,nan,False,Abies pinsapo var. tazaotana|Abuta concolor|Al...,CMAUP (cCollective molecular activities of use...,10.1246/BCSJ.56.3824|10.1246/CL.1983.1643,nan,nan,,C#C/C=C/C[C@H]1O[C@@H]([C@@H](Br)C/C=C/CC)C[C@...,<rdkit.Chem.rdchem.Mol object at 0x7f31b1ad66c0>

### Combine the data bases

In [12]:
import warnings
from rdkit import Chem
from rdkit.Chem import PandasTools
from rdkit import RDLogger
import pandas as pd

# Suppress warnings
RDLogger.DisableLog('rdApp.*')
warnings.filterwarnings('ignore')


def canonicalize_smiles(smi: str) -> str:
    """Convert SMILES to canonical form."""
    try:
        if pd.isna(smi) or not smi:
            return None
        mol = Chem.MolFromSmiles(str(smi))
        if mol:
            return Chem.MolToSmiles(mol, canonical=True)
    except:
        pass
    return None


# Load databases
print("Loading databases...")
npatlasDF = PandasTools.LoadSDF('NPAtlas_np_data.sdf', smilesName='SMILES', molColName='Molecule')
coconutDF = PandasTools.LoadSDF('coconut_np_data.sdf', smilesName='SMILES', molColName='Molecule')

print(f"NPAtlas: {len(npatlasDF)} molecules")
print(f"COCONUT: {len(coconutDF)} molecules")

# Canonicalize and extract essential columns from NPAtlas
print("\nProcessing NPAtlas...")
npatlas_essential = pd.DataFrame({
    'Canonical_SMILES': npatlasDF['compound_smiles'].apply(canonicalize_smiles),
    'InChIKey': npatlasDF['compound_inchikey'],
    'Name': npatlasDF['compound_name'],
    'Molecular_Formula': npatlasDF['compound_molecular_formula'],
    'Molecular_Weight': npatlasDF['compound_molecular_weight'],
    'Database_ID': npatlasDF['npaid'],
    'Database': 'NPAtlas',
    'Origin': npatlasDF['origin_species']
})

# Canonicalize and extract essential columns from COCONUT
print("Processing COCONUT...")
coconut_essential = pd.DataFrame({
    'Canonical_SMILES': coconutDF['canonical_smiles'].apply(canonicalize_smiles),
    'InChIKey': coconutDF['standard_inchi_key'],
    'Name': coconutDF['name'],
    'Molecular_Formula': coconutDF['molecular_formula'],
    'Molecular_Weight': coconutDF['molecular_weight'],
    'Database_ID': coconutDF['identifier'],
    'Database': 'COCONUT',
    'Origin': coconutDF['organisms']
})

# Combine
print("\nCombining...")
naturalProductDF = pd.concat([npatlas_essential, coconut_essential], ignore_index=True)

# Remove invalid SMILES
naturalProductDF = naturalProductDF.dropna(subset=['Canonical_SMILES'])

# Remove duplicates (keep entry with name if available)
naturalProductDF['has_name'] = naturalProductDF['Name'].notna()
naturalProductDF = naturalProductDF.sort_values(by=['Canonical_SMILES', 'has_name'], ascending=[True, False])
naturalProductDF = naturalProductDF.drop_duplicates(subset=['Canonical_SMILES'], keep='first')
naturalProductDF = naturalProductDF.drop(columns=['has_name']).reset_index(drop=True)

# Summary
print("NATURAL PRODUCTS DATABASE")
print(f"Total unique compounds: {len(naturalProductDF)}")
print(f"\nBy database:")
print(naturalProductDF['Database'].value_counts())
print(f"\nColumns: {naturalProductDF.columns.tolist()}")

# Save
naturalProductDF.to_csv('naturalProductDF.csv', index=False)
naturalProductDF.to_parquet('naturalProductDF.parquet', index=False)
print("\nSaved to naturalProductDF.csv and naturalProductDF.parquet")

naturalProductDF

Loading databases...
NPAtlas: 36454 molecules
COCONUT: 715818 molecules

Processing NPAtlas...
Processing COCONUT...

Combining...
NATURAL PRODUCTS DATABASE
Total unique compounds: 721811

By database:
Database
COCONUT    685390
NPAtlas     36421
Name: count, dtype: int64

Columns: ['Canonical_SMILES', 'InChIKey', 'Name', 'Molecular_Formula', 'Molecular_Weight', 'Database_ID', 'Database', 'Origin']

Saved to naturalProductDF.csv and naturalProductDF.parquet

,Canonical_SMILES,InChIKey,Name,Molecular_Formula,Molecular_Weight,Database_ID,Database,Origin
0,B,UORVGPXVDQYIDP-UHFFFAOYSA-N,13283-31-3,BH3,13.84,CNP0600108.0,COCONUT,Erysimum inconspicuum
1,B1Oc2ccccc2O1,CENMEJUYOOMFFZ-UHFFFAOYSA-N,EINECS 205-991-5,C6H5BO2,119.92,CNP0578277.0,COCONUT,Eucalyptus camaldulensis
2,BN1CCC(c2ccc(S(=O)(=O)C3C=CC([N+](=O)[O-])=CC3...,FXIBWASRESHULJ-UHFFFAOYSA-N,"1-boranyl-3-{2-methyl-4-[(4-nitrocyclohexa-2,4...",C17H21BN2O4S,360.24,CNP0567821.0,COCONUT,nan
3,Br,CPELXLSAUQHCOX-UHFFFAOYSA-N,Hydrogen bromide,BrH,80.91,CNP0491843.0,COCONUT,Bugula neritina
4,Br.Br.Br.Br.Br.c1ccc(CN(CCCNCCCCNCC2CC2)CCCNCC...,OZXUQPYSBKKRTN-UHFFFAOYSA-N,BCPM4334/HBr,C29H58Br5N5,876.34,CNP0511039.0,COCONUT,nan
...,...,...,...,...,...,...,...,...
721806,c1scc2c1-c1cscc1-c1cscc1-c1cscc1-2,CBPCBQMVOGRAQT-UHFFFAOYSA-N,56598-43-7,C16H8S4,328.51,CNP0440583.0,COCONUT,nan
721807,c1snnc1-c1csnn1,QXURINNWDWEMQC-UHFFFAOYSA-N,"4-(1,2,3-thiadiazol-4-yl)-1,2,3-thiadiazole",C4H2N4S2,170.22,CNP0464590.0,COCONUT,nan
721808,n1n[nH]c(Nc2nnn[nH]2)n1,RVXHYSAOMMVOCQ-UHFFFAOYSA-N,"5-(1H-1,2,3,4-tetrazol-1-id-5-ylamino)-1H-1,2,...",C2H3N9,153.11,CNP0466262.0,COCONUT,nan
721809,n1noo1,CNTUBXZTTNUMDA-UHFFFAOYSA-N,"1,2,3,4-Dioxadiazete",N2O2,60.01,CNP0564641.0,COCONUT,nan
721810,o1oo1,XQOAKYYZMDCSIA-UHFFFAOYSA-N,Trioxirane,O3,48.0,CNP0556426.0,COCONUT,nan

### generate canonical SMILES from the molecule objects

In [15]:
%%time

import warnings
from rdkit import Chem
from rdkit.Chem import PandasTools, rdMolDescriptors
from rdkit.Chem.inchi import MolToInchi, InchiToInchiKey
from rdkit import RDLogger
import pandas as pd

# Suppress warnings
RDLogger.DisableLog('rdApp.*')
warnings.filterwarnings('ignore')


def mol_to_canonical_smiles(mol) -> str:
    """Convert RDKit mol object to canonical SMILES (same as code-2)."""
    try:
        if mol:
            return Chem.MolToSmiles(mol, canonical=True)
    except:
        pass
    return None


def mol_to_inchikey(mol) -> str:
    """Convert RDKit mol object to InChIKey (same as code-2)."""
    try:
        if mol:
            inchi = MolToInchi(mol)
            if inchi:
                return InchiToInchiKey(inchi)
    except:
        pass
    return None


def get_mol_property(mol, property_names: list) -> str:
    """Get first available property from molecule."""
    if not mol:
        return None
    props = mol.GetPropsAsDict()
    for prop_name in property_names:
        if prop_name in props:
            val = props[prop_name]
            if val and str(val).strip():
                return str(val).strip()
    return None


def process_sdf_to_dataframe(sdf_path: str, database_name: str) -> pd.DataFrame:
    """
    Process SDF file and generate canonical SMILES from molecule objects.
    This mirrors the behavior of code-2's load_natural_products_from_sdf().
    """
    print(f"\nProcessing: {sdf_path}")
    print(f"Database: {database_name}")
    
    # Property mappings (same as code-2)
    name_properties = {
        'npatlas': ['compound_name', 'compound_names', 'npaid', 'name', 'ID'],
        'coconut': ['name', 'coconut_id', 'Name', 'ID', 'compound_name'],
    }
    
    id_properties = {
        'npatlas': ['npaid', 'npatlas_id', 'ID', 'id'],
        'coconut': ['identifier', 'coconut_id', 'ID', 'id'],
    }
    
    source_properties = {
        'npatlas': ['origin_species', 'origin_type', 'genus', 'species'],
        'coconut': ['organisms', 'source', 'organism', 'textTaxa'],
    }
    
    db_key = database_name.lower()
    
    # Load using SDMolSupplier (same as code-2)
    supplier = Chem.SDMolSupplier(sdf_path)
    
    if supplier is None:
        raise ValueError(f"Could not load SDF file: {sdf_path}")
    
    records = []
    valid_count = 0
    error_count = 0
    
    for idx, mol in enumerate(supplier):
        if mol is None:
            error_count += 1
            continue
        
        # Generate canonical SMILES from molecule object (CRITICAL - same as code-2)
        canonical_smiles = mol_to_canonical_smiles(mol)
        if not canonical_smiles:
            error_count += 1
            continue
        
        # Generate InChIKey from molecule object (same as code-2)
        inchikey = mol_to_inchikey(mol)
        
        # Get properties
        name = get_mol_property(mol, name_properties.get(db_key, name_properties['npatlas']))
        db_id = get_mol_property(mol, id_properties.get(db_key, id_properties['npatlas']))
        origin = get_mol_property(mol, source_properties.get(db_key, source_properties['npatlas']))
        
        # Calculate molecular properties from mol object
        try:
            formula = rdMolDescriptors.CalcMolFormula(mol)
            mol_weight = rdMolDescriptors.CalcExactMolWt(mol)
        except:
            formula = None
            mol_weight = None
        
        records.append({
            'Canonical_SMILES': canonical_smiles,
            'InChIKey': inchikey,
            'Name': name,
            'Database_ID': db_id,
            'Origin': origin,
            'Molecular_Formula': formula,
            'Molecular_Weight': mol_weight,
            'Database': database_name
        })
        
        valid_count += 1
        
        if (idx + 1) % 50000 == 0:
            print(f"  Processed {idx + 1} molecules...")
    
    print(f"  Valid: {valid_count}, Errors: {error_count}")
    
    return pd.DataFrame(records)


# Process NPAtlas
print("Creating Natural Products Database")

npatlas_df = process_sdf_to_dataframe(
    'NPAtlas_np_data.sdf', 
    'NPAtlas'
)
print(f"NPAtlas: {len(npatlas_df)} molecules")

# Process COCONUT
coconut_df = process_sdf_to_dataframe(
    'coconut_np_data.sdf', 
    'COCONUT'
)
print(f"COCONUT: {len(coconut_df)} molecules")

# Combine
print("\n" + "-" * 60)
print("Combining and deduplicating...")
naturalProductDF = pd.concat([npatlas_df, coconut_df], ignore_index=True)
print(f"Combined: {len(naturalProductDF)} molecules")

# Remove invalid SMILES
naturalProductDF = naturalProductDF.dropna(subset=['Canonical_SMILES'])
print(f"After removing invalid SMILES: {len(naturalProductDF)} molecules")

# Remove duplicates (keep entry with name if available)
naturalProductDF['has_name'] = naturalProductDF['Name'].notna()
naturalProductDF = naturalProductDF.sort_values(
    by=['Canonical_SMILES', 'has_name', 'Database'],
    ascending=[True, False, True]
)
before_dedup = len(naturalProductDF)
naturalProductDF = naturalProductDF.drop_duplicates(subset=['Canonical_SMILES'], keep='first')
naturalProductDF = naturalProductDF.drop(columns=['has_name']).reset_index(drop=True)

print(f"After deduplication: {len(naturalProductDF)} unique molecules")
print(f"Duplicates removed: {before_dedup - len(naturalProductDF)}")

# Summary
print("\n" + "=" * 60)
print("SUMMARY")
print("=" * 60)
print(f"Total unique compounds: {len(naturalProductDF)}")
print(f"\nBy database:")
print(naturalProductDF['Database'].value_counts())

print(f"\nData quality:")
print(f"  With names: {naturalProductDF['Name'].notna().sum()} ({100*naturalProductDF['Name'].notna().mean():.1f}%)")
print(f"  With InChIKey: {naturalProductDF['InChIKey'].notna().sum()} ({100*naturalProductDF['InChIKey'].notna().mean():.1f}%)")

# Save
print("\n" + "-" * 60)
print("Saving...")
naturalProductDF.to_csv('naturalProductDF.csv', index=False)
naturalProductDF.to_parquet('naturalProductDF.parquet', index=False)
print("Saved to naturalProductDF.csv and naturalProductDF.parquet")

Creating Natural Products Database

Processing: NPAtlas_np_data.sdf
Database: NPAtlas
  Valid: 36454, Errors: 0
NPAtlas: 36454 molecules

Processing: coconut_np_data.sdf
Database: COCONUT
  Processed 50000 molecules...
  Processed 100000 molecules...
  Processed 150000 molecules...
  Processed 200000 molecules...
  Processed 250000 molecules...
  Processed 300000 molecules...
  Processed 350000 molecules...
  Processed 400000 molecules...
  Processed 450000 molecules...
  Processed 500000 molecules...
  Processed 550000 molecules...
  Processed 600000 molecules...
  Processed 650000 molecules...
  Processed 700000 molecules...
  Valid: 715818, Errors: 0
COCONUT: 715818 molecules

------------------------------------------------------------
Combining and deduplicating...
Combined: 752272 molecules
After removing invalid SMILES: 752272 molecules
After deduplication: 720603 unique molecules
Duplicates removed: 31669

============================================================
SUMMARY
============================================================
Total unique compounds: 720603

By database:
Database
COCONUT    714522
NPAtlas      6081
Name: count, dtype: int64

Data quality:
  With names: 720603 (100.0%)
  With InChIKey: 720603 (100.0%)

------------------------------------------------------------
Saving...
Saved to naturalProductDF.csv and naturalProductDF.parquet
CPU times: user 17min 17s, sys: 17.4 s, total: 17min 35s
Wall time: 17min 35s

In [16]:
import pandas as pd
from rdkit import Chem
from rdkit.Chem.inchi import MolToInchi, InchiToInchiKey

# Load the fixed database
df = pd.read_parquet('naturalProductDF.parquet')

# Test: pick a few SMILES and verify they match what code-2 would generate
test_smiles = df['Canonical_SMILES'].head(5).tolist()

print("Verification Test:")
for smi in test_smiles:
    mol = Chem.MolFromSmiles(smi)
    if mol:
        # Re-canonicalize (should be identical)
        recanon = Chem.MolToSmiles(mol, canonical=True)
        match = "✓" if smi == recanon else "✗"
        print(f"  {match} {smi[:50]}...")

Verification Test:
  ✓ B...
  ✓ B1Oc2ccccc2O1...
  ✓ BN1CCC(c2ccc(S(=O)(=O)C3C=CC([N+](=O)[O-])=CC3)cc2...
  ✓ Br...
  ✓ Br.Br.Br.Br.Br.c1ccc(CN(CCCNCCCCNCC2CC2)CCCNCCCCNC...

### database creation script to extract SMILES from the mol object, not from the property

In [18]:
import warnings
from rdkit import Chem
from rdkit.Chem import PandasTools
from rdkit import RDLogger
import pandas as pd

# Suppress warnings
RDLogger.DisableLog('rdApp.*')
warnings.filterwarnings('ignore')


def mol_to_canonical_smiles(mol) -> str:
    """Convert RDKit mol object to canonical SMILES."""
    try:
        if mol is not None:
            return Chem.MolToSmiles(mol, canonical=True)
    except:
        pass
    return None


# Load databases
print("Loading databases...")
npatlasDF = PandasTools.LoadSDF('NPAtlas_np_data.sdf', smilesName='SMILES', molColName='Molecule')
coconutDF = PandasTools.LoadSDF('coconut_np_data.sdf', smilesName='SMILES', molColName='Molecule')

print(f"NPAtlas: {len(npatlasDF)} molecules")
print(f"COCONUT: {len(coconutDF)} molecules")

# === KEY FIX: Extract canonical SMILES from mol object, not from property ===
print("\nProcessing NPAtlas...")
npatlas_essential = pd.DataFrame({
    'Canonical_SMILES': npatlasDF['Molecule'].apply(mol_to_canonical_smiles),  # FROM MOL OBJECT
    'InChIKey': npatlasDF['compound_inchikey'],
    'Name': npatlasDF['compound_name'],
    'Molecular_Formula': npatlasDF['compound_molecular_formula'],
    'Molecular_Weight': npatlasDF['compound_molecular_weight'],
    'Database_ID': npatlasDF['npaid'],
    'Database': 'NPAtlas',
    'Origin': npatlasDF['origin_species']
})

print("Processing COCONUT...")
coconut_essential = pd.DataFrame({
    'Canonical_SMILES': coconutDF['Molecule'].apply(mol_to_canonical_smiles),  # FROM MOL OBJECT
    'InChIKey': coconutDF['standard_inchi_key'],
    'Name': coconutDF['name'],
    'Molecular_Formula': coconutDF['molecular_formula'],
    'Molecular_Weight': coconutDF['molecular_weight'],
    'Database_ID': coconutDF['identifier'],
    'Database': 'COCONUT',
    'Origin': coconutDF['organisms']
})

# Combine
print("\nCombining...")
naturalProductDF = pd.concat([npatlas_essential, coconut_essential], ignore_index=True)

# Remove invalid SMILES
naturalProductDF = naturalProductDF.dropna(subset=['Canonical_SMILES'])

# Remove duplicates (keep entry with name if available)
naturalProductDF['has_name'] = naturalProductDF['Name'].notna()
naturalProductDF = naturalProductDF.sort_values(by=['Canonical_SMILES', 'has_name'], ascending=[True, False])
naturalProductDF = naturalProductDF.drop_duplicates(subset=['Canonical_SMILES'], keep='first')
naturalProductDF = naturalProductDF.drop(columns=['has_name']).reset_index(drop=True)

# Summary
print("\n" + "=" * 50)
print("NATURAL PRODUCTS DATABASE")
print("=" * 50)
print(f"Total unique compounds: {len(naturalProductDF)}")
print(f"\nBy database:")
print(naturalProductDF['Database'].value_counts())
print(f"\nColumns: {naturalProductDF.columns.tolist()}")

# Save
naturalProductDF.to_csv('naturalProductDF2.csv', index=False)
naturalProductDF.to_parquet('naturalProductDF2.parquet', index=False)
print("\nSaved to naturalProductDF.csv and naturalProductDF.parquet")

Loading databases...

Failed to patch pandas - unable to change molecule rendering
Failed to patch pandas - unable to change molecule rendering

NPAtlas: 36454 molecules
COCONUT: 715818 molecules

Processing NPAtlas...
Processing COCONUT...

Combining...

==================================================
NATURAL PRODUCTS DATABASE
==================================================
Total unique compounds: 720603

By database:
Database
COCONUT    684187
NPAtlas     36416
Name: count, dtype: int64

Columns: ['Canonical_SMILES', 'InChIKey', 'Name', 'Molecular_Formula', 'Molecular_Weight', 'Database_ID', 'Database', 'Origin']

Saved to naturalProductDF.csv and naturalProductDF.parquet